export default {
  TeachMe: require('../assets/images/TeachMe.png'),
  FloatingAddbtn: require('../assets/images/FloatingAddbtn.png'),
  TeachMePressed: require('../assets/images/TeachMePressed.png'),
  Avatar: require('../assets/images/Avatar.png'),
  SendMsg: require('../assets/images/SendMsg.png'),
  ScreenShot20211122At33505PM: require('../assets/images/ScreenShot20211122At33505PM.png'),
  _3185947: require('../assets/images/3185947.jpg'),
  Business3dCasualLife3dWomanInSuitNextToSmartphoneScreenShowingNotifications: require('../assets/images/Business3dCasualLife3dWomanInSuitNextToSmartphoneScreenShowingNotifications.png'),
  CasualLife3dBoyInSuperheroCapeRunning: require('../assets/images/CasualLife3dBoyInSuperheroCapeRunning.png'),
  CasualLife3dYoungWomanImaginingThingsWhileReadingEBook: require('../assets/images/CasualLife3dYoungWomanImaginingThingsWhileReadingEBook.png'),
  Frame128: require('../assets/images/Frame128.png'),
  CasualLife3dSearchBarWithMicroscopeAndMiniaturePlanetsOnTop: require('../assets/images/CasualLife3dSearchBarWithMicroscopeAndMiniaturePlanetsOnTop.png'),
  Sky: require('../assets/images/Sky.jpg'),
  LogoOnboardingCAS: require('../assets/images/LogoOnboardingCAS.png'),
  IphoneBackgroundWhite: require('../assets/images/IphoneBackgroundWhite.png'),
  ScreenShot20220523At17091: require('../assets/images/ScreenShot20220523At17091.png'),
  StaticImage: require('../assets/images/StaticImage.png'),
};
